### PR TITLE
added safety precaution for turret

### PR DESCRIPTION
**Pull request by eusmanova**
issue (hopefully solved): if turret encoder gets unplugged at any time, turret would either be trying to track target or go home, both methods which rely on a steadily updated tick count (otherwise, the turret would spin indefinitely)

### CODE REVIEW

**Comment by Rodney-Lewis** [comment]
First, initTurretTime isn't set to anything and then it is called without a value in the updateTurretTicks method. This should be given some default value.

I believe this need some a small deadband of some sort due it being a double. There will also a be brief period in which those values would be the same even in a working system. 
https://github.com/FRC-1250/Team-1250-InfiniteRecharge2020/blob/0256cd1ca4905e052d6c5b933a9e335136784a10/src/main/java/frc/robot/subsystems/Sub_Shooter.java#L205-L217

For example, on startup this should prevent movement. Assuming we start at ticks = 0..

1) RobotContainer.s_shooter.updateTurretTicks() runs...
2) We wait 3/4s of a second...
3) We set init time to new current time
4) We set prevTurretTicks to getTurretTicks() (which returns 0)
5) If we try to move the turrent now..
6) If prevTickets is equivalent to  getTurretTicks() (still returns 0 and prevTickets is also set to 0)
7) We don't move.

Since there isn't a good way to really know if the turret is actually dead or if we're simply just not moving I don't believe there is a good way to handle this scenario. Looking into it... Maybe sticky faults.. or this is a team task to test this between matches and we provide a manual way to aim the turret.

**Comment by Rodney-Lewis** [comment]
The only way I see us being able to verify if it it's actually alive is by putting it in motion first and then checking which by itself may be unsafe. 

1) Mark your starting point.
2) Put the turret in motion.
3) Check after some time that your current tickets aren't the same as your starting point,
4) If they're the same but we know the turret moved based we moved it... then ticket feedback failed.
5) Else if the tickets are different at all, then we're okay.

We would have to effectively do this every time we want to move the turret but this would effectively delay our movements because we have to make sure we're healthy by crawling first before we're good to just run.

If we have a genuine concern for the encoder being unplugged we need to provide..
1) A manual way to control the turret
2) A override to disable tracking and return to home

BUT I highly believe that the actual solution is to ensure that this is checked **every single match** by the drive team or pit crew OR we consider switching motors altogether if possible.

**Comment by FRC-1250** [comment]
> The only way I see us being able to verify if it it's actually alive is by putting it in motion first and then checking which by itself may be unsafe.
> 
This would happen immediately. If it doesn't start moving the moment the robot is enabled, that means it's working (initially, at least). I agree that a pit check would still be most helpful, because that allows the issue to be fixed (if encoder is unplugged, plug it back in), but if that's not possible or forgotten, I think this is the best we can do from software side of things.
A manual "stopTurret" command would be helpful mid-match, but there's so much that could go wrong when you consider a human has to first recognize the issue and then press the button.
I'll add a default initTurretTime (perhaps a negative would work because it doesn't risk ever falsely hitting it). I'm loath to discard this because I think there's hope (and it could be another diagnostic LED), but if there's really no good way to go about it, we can probably live with just putting it on the list of things to manually check pre-match (Elena is making that list).

**Comment by FRC-1250** [comment]
> Since there isn't a good way to really know if the turret is actually dead or if we're simply just not moving

The way I did it is through "if (turretTalon.getMotorOutputPercent() > 0) {". If we're trying to move (tracking or going home), then motor output is greater than 0 and so the logic continues. However, if we're done moving (centered on target or at home), then the motor output is set to 0 in the track() and goHome() methods, which would then make it so that the "turret encoder check" logic doesn't happen, which I think eliminates the question of "are we unplugged or supposed to not be moving?"

**Comment by Rodney-Lewis** [comment]
Where do you set it to move first? If the setTurrentSpeed is involved in this logic and is the only entry point into making the turret move, then it can't move because it's never moving initially to be true against if (turretTalon.getMotorOutputPercent() > 0). There is a difference between tracking if we're already moving vs making it move.

RobotContainer.s_shooter.updateTurretTicks() is always running so the previousTicks is always being set. If we're sitting still, then we set the previous to the current. So this logic is always running just due to to where it is.

**Comment by FRC-1250** [comment]
All commands that move the turret use spinTurretMotor(speed), which has the first check of (shouldTurretMove() && enabledTurret). By default, enabledTurret is true, so that part of the logic should be fine in the first loop. 
```
public boolean shouldTurretMove() {
    if (turretTalon.getMotorOutputPercent() > 0) {
      if (prevTurretTicks == getTurretTicks()) {
        return false;
      } else {
        return true;
      }
    }
    return true;
  }
```

Then, the first loop of shouldTurretMove() checks if the motor is moving (the getMotorOutputPercent). Since we're currently in the process of trying to move the turret, the output percent should be 0, which would make the logic skip the if and return true.

```
public void spinTurretMotor(double speed) {
    if (shouldTurretMove() && enabledTurret) {
      turretTalon.set(speed);
    } else {
      turretTalon.set(0);
      enabledTurret = false;
    }
  }
```

So now we know that shouldTurretMove() returns true and enabledTurret returns true, so turretTalon gets set to a speed (which then sets the motorOutputPercent to that speed) and should start changing the tick count. Then, in the next loop, motorOutputPercent is >0 and ticks should be different from ticks 3/4ths of a second prior.

**Pull request merged**
